# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^adapters/
      - id: end-of-file-fixer
        exclude: ^adapters/
      - id: check-yaml
        exclude: ^infrastructure/|^adapters/
      - id: check-json
        exclude: ^adapters/
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        exclude: ^adapters/|^knowledge/
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: ^lab/|^adapters/
